version: '3.7'
services:
  frontend:
    image: node:16
    volumes:
    - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports: 
      - 3000:3000
  backend:
    image: node:16
    volumes:
    - ./backend:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports: 
      - 4000:4000
networks:
  front:
    driver: bridge